[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/..."
type = "service_account"
project_id = "garage-project-495611"
private_key_id = "48777139dbf4e5a58072f746e89faf8eb75405b"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEv....\n-----END PRIVATE KEY-----\n"
client_email = "garage-robot@garage-project-495611.iam.gserviceaccount.com"
client_id = "107549056864621394105"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/garage-robot%40garage-project-495611.iam.gserviceaccount.com"